name: Test workflow for example 01

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: NPM install and build
        run: npm install && npm build
      - name: Test Verified Commit
        uses: ./
        with:
          appId: ${{ secrets.APP_ID }}
          clientId: ${{ secrets.CLIENT_ID }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
      - name: "Commit and push changes"
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          (git commit -m "Build index.js") || true
          (git push) || true